### ISSUE TITLE
"Installation Details" popup does not update when opened in the "Details" page

### ISSUE THREAD

**Issue by asarium** [ngld/old-knossos#70] opened 2017-11-10 09:28 UTC
When I install a mod from the Details page and then click on the "Installing..." button then the progress bars are frozen and won't update until the dialog is reopened. The progress report works a expected when opened on any of the other pages.

**Comment by ngld** [comment] 2017-11-10 09:35
The problem is that while the details page copies a reference to the `progress_info` object, that object is replaced each time the progress updates.
One possible solution would be to update that object instead of replacing it but that might break Vue.

**Comment by ngld** [comment] 2017-12-28 21:44
This should be fixed in 0.7.2, please reopen if it still occurs.

**Closed as completed by ngld** 2017-12-28 21:44 UTC
Labels: bug
